#!/usr/bin/bash
mkdir ipfs
cp -r css fonts img js index.html ipfs/
sed -i 's/^.*IPFSLINK.*$//' ipfs/index.html

cid=$(ipfs add -Qr ipfs/)
echo "Added to IPFS: $cid"

# flag is only for testing purposes
if [ "$1" != "--no-preserve-dir" ]; then
  rm -rf ipfs
fi

sed -ri "s/IPFSLINK href=\"[^\"]*\"/IPFSLINK href=\"https:\/\/ipfs.io\/ipfs\/$cid\"/" index.html
git add index.html
git commit -m "Update IPFS link"
